name: Docker Release CI

on:
  push:
    branches: [ master ]

jobs:
  tweet:
    runs-on: ubuntu-latest
    name: Tweet
    steps:
    - uses: actions/checkout@v2
    - name: Test Get Commit
      run: echo "::set-output name=msg::$(git log -1 HEAD --pretty=format:%s)"
    - name: Echo Variable
      run: echo ${msg}
    