name: Docker Release CI

on:
  push:
    branches: [ master ]

jobs:
  tweet:
    runs-on: ubuntu-latest
    name: Tweet
    steps:
    - uses: actions/checkout@v2
    - name: Test Get Commit
      with:
        test_var : "Commit message $(git log -1 HEAD --pretty=format:%s)"
      run: echo $test_var
    